### ISSUE TITLE
Add support for `location='view_args'`

### ISSUE THREAD

**Issue by teodorkostov** [apiflask/apiflask#301]
To validate path arguments with `webargs` the location value that has to be used is `view_args`. Documentation [link](https://webargs.readthedocs.io/en/latest/api.html#webargs.flaskparser.FlaskParser.load_view_args).

The following code
```python
from webargs.flaskparser import use_args
@use_args(IdSchema, location='view_args')
```

should be possible to be written as
```python
from apiflask import APIFlask
app = APIFlask(__name__)
@app.input(IdSchema, location='view_args')
```

**Comment by greyli** [comment]
Thanks for reporting on this. I will add the `path` and `view_args` locations later.

I have some doubts about this. If a view accepts a path schema, then the view function will have to declare both the path variables (one by one) and the path schema data:

```py
@app.get('/pets/<id>/<name>/<category>')
@app.input(PathSchema, location='path')
def hello(id, name, category, path_data):
```

Is it the correct usage?

**Comment by teodorkostov** [comment]
@greyli Correct. Unfortunately, the `path_data` is passed as another dictionary after all the path arguments. I do not know the reasoning behind it but this is the implementation from `webargs`.

Thank you for this fix!

**Comment by davidcornell2326** [comment]
@teodorkostov I know this is an old ticket, but this is the only reference I can find to this fact that using `location='path'` then means you would have to declare the path variables AND the path data schema, as @greyli showed above. Is there any way around this? Any way to force the `@app.get(...)` to NOT inject the path variables? This isn't a functional problem, but it leads to unused variables which is not the cleanest. The only other approach I have found is setting `arg_name="_"` and setting the path schema variable name to `_` just so that it is clear that only one of the two options is being used. But I would like to be able to only have one arg in the function, that being the `path_data` arg.

**Comment by gundam78** [comment]
@davidcornell2326 I encountered this situation recently. My solution is adding  an unused `**kwargs `to absorb the view args. Looking forward to the improvement.
