### ISSUE TITLE
Use pytest autouse fixture in /tests/test_async.py

### ISSUE THREAD

**Issue by jonasps** [apiflask/apiflask#318]
I suggest using a fixture for the "skip async test" function since all test in that file will requires Flask > 2.0

**apiflask/tests/test_async.py**
```
@pytest.fixture(autouse=True)
def skip_async_test(app):
    if not hasattr(app, 'ensure_sync'):
        pytest.skip('This test requires Flask 2.0 or higher')
```

**Comment by greyli** [comment]
Good point! Feel free to make a PR.

**Comment by 9gl** [comment]
Hey @greyli @jonasps  , I'm interested in contributing to this issue, so before I start working on it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started .

**Comment by greyli** [comment]
> Hey @greyli @jonasps , I'm interested in contributing to this issue, so before I start working on it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started .

The `tests/test_async.py` file is used to test async-related functionalities, these tests are targeted to Flask 2, so I created a [`skip_flask1`](https://github.com/apiflask/apiflask/blob/main/tests/test_async.py#L8) function and call it in each test function to skip the test for Flask 1.

To improve it, you can create an autouse fixture to apply the function to all the tests in that module. Since @jonasps already gave the code snippet, you can paste it to the top of the `tests/test_async.py` file, then remove the existing `skip_flask1` function and all the calls of this function.
