### ISSUE TITLE
minimum flask version differs between website info and github code

### ISSUE THREAD

**Issue by icarocd** [apiflask/apiflask#478]
According to your website, minimum flask version is 2.0.0.
However, by checking your code, I can see your tags >= 2.0 request flask 2.2.0 instead.
I have a large project using flask 2.1.2, and it would demand a large effort to upgrade it to flask 2.2.0.
Do you really need flask >= 2.2.0? Could it be 2.1.2?
Thanks in advance.

**Comment by wlach** [comment]
> In a similar boat, using 2.0.3 and would prefer not to have to upgrade at this time.

I experimented with this in a pull request. It looks like some of the examples which we use for testing depend on more recent features. What do you think @greyli? We could either fix them or increase the dependency. Personally I would prefer not to have to upgrade Flask but I understand as a maintainer it might be easier to just bump the requirement and calling it a day.

**Comment by greyli** [comment]
I'm Okay to loosen the version to 2.0.

I pin to > 2.2 because I added the list return value support back to Flask 2.2, and then I removed the related code in APIFlask.

@wlach To change it back to 2.0, you will also need to add [this method](https://github.com/apiflask/apiflask/pull/451/files#diff-364d110d4b7e5187438ab8fbbf50b027073da6a0009a71e85780e49347a6e3b1L401-L413) back.

**Comment by greyli** [comment]
@icarocd @wlach [2.0.2](https://github.com/apiflask/apiflask/releases/tag/2.0.2) released. Thanks for the feedback and improvement!
